<a href="https://colab.research.google.com/github/Sancheuz123/KSVD/blob/main/%D0%9B%D0%A0_1_%D0%93%D0%B0%D0%B9%D0%B2%D0%BE%D1%80%D0%BE%D0%BD%D1%81%D1%8C%D0%BA%D0%B8%D0%B9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі



In [ ]:
import numpy as np
np.__version__


'2.0.2'

In [ ]:
v = np.array([1, 2, 3, 4, 5], dtype = float)
v

array([1., 2., 3., 4., 5.])

In [ ]:
v[0]

np.float64(1.0)

In [ ]:
v[-1]

np.float64(5.0)

In [ ]:
a = np.array([[5,2,7], [4,9,6]])
a

array([[5, 2, 7],
       [4, 9, 6]])

In [ ]:
a[1,2]

np.int64(6)

In [ ]:
a[0,0]

np.int64(5)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

6

In [ ]:
a.shape

(2, 3)

In [ ]:
a = np.array([[3,4,6], [9,5,8], [6,8,5]])
a

array([[3, 4, 6],
       [9, 5, 8],
       [6, 8, 5]])

In [ ]:
b = np.matrix([[6,7,3], [6,4,9], [3,7,5]])
b

matrix([[6, 7, 3],
        [6, 4, 9],
        [3, 7, 5]])

In [ ]:
diag_a = np.diag(a)
diag_a

array([3, 5, 5])

In [ ]:
diag_b = np.diag(b)
diag_b

array([6, 4, 5])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.random.randint(11, size=(4,4) )

array([[10, 10,  8,  9],
       [ 7,  1,  3,  7],
       [10,  7,  4,  5],
       [ 1,  7,  2,  2]])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.array([[3,6,7], [3,1,8], [6,9,3]])
a

array([[3, 6, 7],
       [3, 1, 8],
       [6, 9, 3]])

In [ ]:
a.transpose()

array([[3, 3, 6],
       [6, 1, 9],
       [7, 8, 3]])

In [ ]:
a.T

array([[3, 3, 6],
       [6, 1, 9],
       [7, 8, 3]])

In [ ]:
a = np.array([[9,6], [4,1] ])
a

array([[9, 6],
       [4, 1]])

In [ ]:
a_det = np.linalg.det(a)
a_det

np.float64(-15.0)

In [ ]:
a = np.matrix([[5, 7, 9], [4, 8, 1]])
c = 3 * a
c

matrix([[15, 21, 27],
        [12, 24,  3]])

In [ ]:
a = np.matrix([[9, 6, 5], [7, 2, 5]])
b = np.matrix([[8, 3, 6], [6, 2, 10]])
c = a + b
c

matrix([[17,  9, 11],
        [13,  4, 15]])

In [ ]:
a = np.matrix([[5, 2], [4, 9]])
b = np.matrix([[3, 8], [4, 1]])
c = np.dot(a, b)
c

matrix([[23, 42],
        [48, 41]])

In [ ]:
np.multiply(a, b)

matrix([[15, 16],
        [16,  9]])

In [ ]:
a/b

matrix([[1.66666667, 0.25      ],
        [1.        , 9.        ]])

In [ ]:
np.divide(a, b)

matrix([[1.66666667, 0.25      ],
        [1.        , 9.        ]])

In [ ]:
a = np.matrix([[-9, 6], [8, 5]])

a_inv = np.linalg.inv(a)
a_inv

matrix([[-0.05376344,  0.06451613],
        [ 0.08602151,  0.09677419]])

In [ ]:
rank = np.linalg.matrix_rank(a)
rank

np.int64(2)

In [ ]:
a = np.array([[1, 9, 3], [5, 2, 10]])
b = np.array([[8, 1, 3], [5, 9, 9]])

c1 =  a*b
print("Поелементний добуток матриць:")
print(c1)

Поелементний добуток матриць:
[[ 8  9  9]
 [25 18 90]]


In [ ]:
a = np.array([[3,6,7], [3,1,8], [6,9,3]])

eigenvalues, eigenvectors = np.linalg.eig(a)


In [ ]:
print("В:")
eigenvalues

В:


array([15.35666828, -1.7028759 , -6.65379238])

In [ ]:
print("ВВ:")
eigenvectors

ВВ:


array([[-0.59722222, -0.85754331, -0.07016644],
       [-0.4820248 ,  0.4901999 , -0.70751364],
       [-0.64107544,  0.15596005,  0.70320773]])